name: Build Modular Scripts

on:
  push:
    paths:
      - "models/modules/**/code/*.luau"
      - "standards/MODULAR/code/1.0.0/*.luau"

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Run build script
        run: python build_modules.py

      - name: Commit built files
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add models/modules/*/*.luau
          git commit -m "chore: rebuild modules" || echo "No changes to commit"
          git push
